/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laptrinhmang_doan;

/**
 *
 * @author HOANG MINH HUY
 */
public class ThongKenCoViPanel extends javax.swing.JPanel {

    /**
     * Creates new form ThongKenCoViPanel
     */
    public ThongKenCoViPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        PanelAllCovid = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        soCaTulabel = new javax.swing.JLabel();
        soCaTulabel2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        PanelAllCovid1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        soCaTulabel3 = new javax.swing.JLabel();
        soCaTulabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1130, 840));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(51, 204, 0));
        jPanel2.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jPanel2);
        jPanel2.setBounds(31, 19, 0, 0);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1130, 840));
        jPanel3.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(51, 204, 0));
        jPanel4.setLayout(new java.awt.BorderLayout());
        jPanel3.add(jPanel4);
        jPanel4.setBounds(31, 19, 0, 0);

        PanelAllCovid.setLayout(null);

        jLabel5.setText("Số ca: ");
        PanelAllCovid.add(jLabel5);
        jLabel5.setBounds(20, 10, 70, 30);

        soCaTulabel.setText("+00000");
        PanelAllCovid.add(soCaTulabel);
        soCaTulabel.setBounds(20, 120, 140, 40);

        soCaTulabel2.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        soCaTulabel2.setText("00000");
        PanelAllCovid.add(soCaTulabel2);
        soCaTulabel2.setBounds(20, 50, 180, 60);

        jPanel3.add(PanelAllCovid);
        PanelAllCovid.setBounds(20, 10, 380, 170);

        jPanel8.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Số ca nhiễm");
        jPanel8.add(jLabel8);
        jLabel8.setBounds(10, 10, 150, 40);

        jPanel3.add(jPanel8);
        jPanel8.setBounds(0, 530, 550, 260);

        jPanel9.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Số ca tử vong");
        jPanel9.add(jLabel9);
        jLabel9.setBounds(20, 10, 170, 40);

        jPanel3.add(jPanel9);
        jPanel9.setBounds(550, 530, 580, 260);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel11.setText("Biểu đồ");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(10, 470, 170, 60);

        PanelAllCovid1.setLayout(null);

        jLabel12.setText("Số ca tử vong: ");
        PanelAllCovid1.add(jLabel12);
        jLabel12.setBounds(20, 10, 110, 30);

        soCaTulabel3.setText("+00000");
        PanelAllCovid1.add(soCaTulabel3);
        soCaTulabel3.setBounds(20, 120, 140, 40);

        soCaTulabel4.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        soCaTulabel4.setText("00000");
        PanelAllCovid1.add(soCaTulabel4);
        soCaTulabel4.setBounds(20, 50, 180, 60);

        jPanel3.add(PanelAllCovid1);
        PanelAllCovid1.setBounds(410, 10, 380, 170);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jTable1.setToolTipText("Địa điểm\nSố ca\nSố ca tử vong");
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1130, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1130, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 3, Short.MAX_VALUE)))
        );

        jPanel3.add(jPanel5);
        jPanel5.setBounds(0, 180, 1130, 300);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 1130, 840);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1130, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAllCovid;
    private javax.swing.JPanel PanelAllCovid1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel soCaTulabel;
    private javax.swing.JLabel soCaTulabel2;
    private javax.swing.JLabel soCaTulabel3;
    private javax.swing.JLabel soCaTulabel4;
    // End of variables declaration//GEN-END:variables
}
